### ISSUE TITLE
Overwhelming amount of papers

### ISSUE THREAD

**Issue by joaquincabezas** [AstraZeneca/awesome-explainable-graph-reasoning#13]
Hi, I have been impressed about how fast is this field growing. As I continue reading and learning, I will contribute with papers to make this list even better.

In particular, @flyingdoog is maintaining a list with the papers (grouped by year) at https://github.com/flyingdoog/awesome-graph-explainability-papers that can be interesting to review

**Comment by Ppr1999** [comment]
That's good @joaquincabezas
