### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Java-Mx** [AstraZeneca/awesome-explainable-graph-reasoning#14]
**I really like your work ! Keep it up**

**Comment by benedekrozemberczki** [comment]
Thank you @Java-Mx! Feel free to follow the contributors! We will have cool new stuff out soon.

**Comment by Java-Mx** [comment]
**Yeah !**

**Comment by Java-Mx** [comment]
> Thank you @Java-Mx! Feel free to follow the contributors! We will have cool new stuff out soon.

_**Yes ! Nice Keep it up. You are doing a wonderful work 👏 **_
